### ISSUE TITLE
アカウント新規作成後の流れ

### ISSUE THREAD

**Issue by Toshiaki0315** [classmethod/grafana_dashboard_handson#3]
## セクション名、場所
アカウントを新規作成した後

## 現状の記述
ログイン後にスタックを選択になっている

## 問題点 / 改善提案
実際はログインされた状態になっている

この画面
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/a964507c-3e04-4d25-9b61-2bd00e3b7f65">

## 期待される結果（任意）
初心者ほど、アカウントを新規作成するので上記の画面からの流れもあった方がいい。

## 環境情報（任意）
- OS: [例: Windows 10, macOS Big Sur]
- ブラウザ: [例: Chrome 91, Firefox 89]
- Grafanaのバージョン: [例: 8.0.6]

## 緊急度

- [ ] 高 (ハンズオンの進行を妨げる)
- [ ] 中 (ハンズオンは進行可能だが、大きな混乱を招く)
- [x] 低 (小さな問題や改善提案)

**Comment by HamadaKoji** [comment]
了解です。このあたり、完全に新規アカウントじゃないとわからない部分でしたね。最初補足できるようにしてみます。

**Comment by HamadaKoji** [comment]
以下の内容を追記済み

ログイン直後、以下のようなeasy setpガイドが表示されたら、一旦なにもせずに、右上の「I'm already familar with Grafana. Skip setup」をクリックしてください。

```
![start setup](../images/start_setup.png)
```
