### ISSUE TITLE
Data Sourcesの時にTestDataが出てこない。

### ISSUE THREAD

**Issue by Toshiaki0315** [classmethod/grafana_dashboard_handson#4]
## 現状の記述
2. [Connections]メニューの中の[Data sources]をクリック。
3. 検索バーにTestDataと入力。

## 問題点 / 改善提案
2と3の操作の前に右上の「Add new data source」ボタンを押す必要がある。

## スクリーンショット（任意）

<img width="1116" alt="image" src="https://github.com/user-attachments/assets/f82f01b7-ac55-49ff-ba93-2f714d16a1c7">

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/b8a5be2e-e76d-4d39-8415-a897444f0768">

## 環境情報（任意）
- OS: [例: Windows 10, macOS Big Sur]
- ブラウザ: [例: Chrome 91, Firefox 89]
- Grafanaのバージョン: [例: 8.0.6]

## 緊急度

- [ ] 高 (ハンズオンの進行を妨げる)
- [ ] 中 (ハンズオンは進行可能だが、大きな混乱を招く)
- [ ] 低 (小さな問題や改善提案)

**Comment by classakky** [comment]
補足します

Connection→DatasoucesからAdd Datas ourceをクリックするか、Connection→Add new connectionを選択した後に、Test DataのOverviewを表示した後に、Add new data sourceをクリックし
<img width="1128" alt="chrome_RPD2ZXhD7b" src="https://github.com/user-attachments/assets/f576ed26-15ae-482d-bbb8-94e4abb94e0b">
さらにSave & testをクリックする必要あり
<img width="1128" alt="chrome_tlR8SLLvoB" src="https://github.com/user-attachments/assets/11090a0f-3830-467a-b1d9-271c6ccd0b32">

**Comment by HamadaKoji** [comment]
ハンズオン手順書反映済み。
