### ISSUE TITLE
ダッシュボードの作成

### ISSUE THREAD

**Issue by Toshiaki0315** [classmethod/grafana_dashboard_handson#5]
## セクション名、場所
Create dashboardとなっているが右のNewをクリックしてNew dashboardを選択する必要がある。

## スクリーンショット（任意）
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/ee58e2dd-d1bc-4958-aa51-f364770e2fd7">

## 環境情報（任意）
- OS: [例: Windows 10, macOS Big Sur]
- ブラウザ: [例: Chrome 91, Firefox 89]
- Grafanaのバージョン: [例: 8.0.6]

## 緊急度

- [ ] 高 (ハンズオンの進行を妨げる)
- [ ] 中 (ハンズオンは進行可能だが、大きな混乱を招く)
- [ ] 低 (小さな問題や改善提案)

**Comment by HamadaKoji** [comment]
手順書修正済み。
