### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by Toshiaki0315** [classmethod/grafana_dashboard_handson#6]
## セクション名、場所
[ADd visualization]　→ [Add visualization]

## 環境情報（任意）
- OS: [例: Windows 10, macOS Big Sur]
- ブラウザ: [例: Chrome 91, Firefox 89]
- Grafanaのバージョン: [例: 8.0.6]

## 緊急度

- [ ] 高 (ハンズオンの進行を妨げる)
- [ ] 中 (ハンズオンは進行可能だが、大きな混乱を招く)
- [ ] 低 (小さな問題や改善提案)

**Comment by HamadaKoji** [comment]
修正済み
