### ISSUE TITLE
[Standard options]セクションの[Unit]の選択肢について

### ISSUE THREAD

**Issue by Toshiaki0315** [classmethod/grafana_dashboard_handson#8]
## 現状の記述
[Standard options]セクションで、[Unit]を[percent (0-100)]に変更。

## 問題点 / 改善提案
選択肢にpercent (0-100)は出てこない。
入力はできる

## スクリーンショット（任意）
<img width="327" alt="image" src="https://github.com/user-attachments/assets/6b745a8c-65f2-42fe-87f8-5a72a5dae55a">

入力した時
<img width="292" alt="image" src="https://github.com/user-attachments/assets/b1097b8d-f86b-4b84-a0f3-0f71178ee6a0">

## 環境情報（任意）
- OS: [例: Windows 10, macOS Big Sur]
- ブラウザ: [例: Chrome 91, Firefox 89]
- Grafanaのバージョン: [例: 8.0.6]

## 緊急度

- [ ] 高 (ハンズオンの進行を妨げる)
- [ ] 中 (ハンズオンは進行可能だが、大きな混乱を招く)
- [ ] 低 (小さな問題や改善提案)

**Comment by Toshiaki0315** [comment]
Miscを入力すると補完で出てくる。
<img width="271" alt="image" src="https://github.com/user-attachments/assets/f8e4cb2e-e12f-4270-b9e1-883acc558ec6">

**Comment by classakky** [comment]
まずMiscを選択すると、percent(0-100)が出てくるという説明になるといいかもしれません
